language: ruby
rvm:
- 2.0.0
script: /bin/bash gh-publisher-scripts/gh-publisher.sh
before_install:
- sudo apt-get update -y
- sudo apt-get install -y
     inkscape
     texlive-full
     texlive-fonts-recommended
     texlive-latex-extra
     texlive-latex-recommended
     texlive-xetex
     texlive-publishers
     #- yes "" | sudo add-apt-repository ppa:jonathonf/texlive-2017
     #- sudo apt-get update -y
     #- sudo apt-get install -y
     #     inkscape
     #     texlive-fonts-recommended
     #     texlive-latex-extra
     #     texlive-latex-recommended
     #     texlive-xetex
